# Generated by Django 5.1.3 on 2024-12-19 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_car_added_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
