# Generated by Django 5.1.3 on 2024-12-25 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_car_favorites_alter_review_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='favorited_by',
        ),
        migrations.RemoveField(
            model_name='car',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorites',
        ),
        migrations.AddField(
            model_name='car',
            name='favorite_cars',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_cars',
            field=models.ManyToManyField(related_name='favorited_by', to='inventory.car'),
        ),
    ]
